name: Build and Push Docker Image

on:
  release:
    types: [published]

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - 
        name: Checkout
        uses: actions/checkout@v4
      
      - 
        name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      
      - 
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      
      - 
        name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      
      - 
        name: Docker meta
        id: meta
        uses: docker/metadata-action@v5
        with:
          # ⚠️ IMPORTANT: Replace 'yoanbernabeu' with your Docker Hub username
          # Format: <dockerhub-username>/<image-name>
          images: |
            yoanbernabeu/s3-doc-mcp
          tags: |
            # Full version tag (e.g., 1.2.3)
            type=semver,pattern={{version}}
            # Major.minor tag (e.g., 1.2)
            type=semver,pattern={{major}}.{{minor}}
            # Major version only (e.g., 1) - disabled for 0.x versions
            type=semver,pattern={{major}},enable=${{ !startsWith(github.ref, 'refs/tags/v0.') }}
            # Latest tag
            type=raw,value=latest,enable={{is_default_branch}}
          flavor: |
            latest=auto
      
      - 
        name: Build and push
        uses: docker/build-push-action@v6
        with:
          context: .
          platforms: linux/amd64,linux/arm64
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          # ⚠️ IMPORTANT: Replace 'yoanbernabeu' with your Docker Hub username
          cache-from: type=registry,ref=yoanbernabeu/s3-doc-mcp:buildcache
          cache-to: type=registry,ref=yoanbernabeu/s3-doc-mcp:buildcache,mode=max

